#spring.data.mongodb.database=testdb
#spring.data.mongodb.port=27017
#spring.data.mongodb.host=mongocontainer

spring:
  data:
    mongodb:
      database: testdb
      port: 27017
      host: mongocontainer